version: '3.8'
services:
  bankdb:
    image: library/postgres:13-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=bankdb
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro